services:

    lucee:
        image: lucee/lucee:latest
        container_name: lucee_website
        environment:
            - LUCEE_ADMIN_PASSWORD=qwerty
        ports:
            - "4433:8888"
        volumes:
            - ./www:/var/www:Z
            - ./config/lucee-web:/opt/lucee/web:Z
            - ./config/lucee-server:/opt/lucee/server:Z


