
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events { }

http {

    server {
        listen 3456;
        server_name _;

        proxy_connect_timeout 10s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
        send_timeout          60s;

        location / {
            proxy_pass http://10.1.10.1:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_buffering on;
        }
    }
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80;


        location / {
            try_files $uri $uri/ $uri.cfm @lucee;
        }

        location @lucee {
            proxy_pass http://lucee:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # server {
    #     listen 80;
    #     
    #     location / {
    #         proxy_pass http://lucee:8888;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #     }
    # }

}



# http {
#     include       /etc/nginx/mime.types;
#     default_type  application/octet-stream;
# 
#     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                       '$status $body_bytes_sent "$http_referer" '
#                       '"$http_user_agent" "$http_x_forwarded_for"';
# 
#     access_log  /var/log/nginx/access.log  main;
# 
#     sendfile        on;
#     #tcp_nopush     on;
# 
#     keepalive_timeout  65;
# 
#     #gzip  on;
# 
#     include /etc/nginx/conf.d/*.conf;
# }
